version: "3"
  
services:
    app:
      build: .
      command: npm start:dev
      ports:
        - '3000:3000'
      volumes:
        - .:/usr/app

    mysql:
      container_name: mysql
      restart: unless-stopped
      command: --default-authentication-plugin=mysql_native_password
      image: mysql:8.0
      environment:
        SERVICE_NAME: "mysql"
        MYSQL_ROOT_NAME: "root"
        MYSQL_ROOT_PASSWORD: "root"     
      ports:
        - "3307:3307"
      volumes:
        - ./docker/mysql-init/mysql-init.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      networks:
        - node

volumes:
  mysql:
    driver: local         

networks:
  node:
    driver: bridge